apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: shoot-network-traffic-gauger-agents
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: shoot
spec:
  authorization:
    credentials:
      name: shoot-access-prometheus-shoot
      key: token
  scheme: HTTPS
  tlsConfig:
    insecureSkipVerify: true
  kubernetesSDConfigs:
  - apiServer: https://kube-apiserver
    authorization:
      credentials:
        name: shoot-access-prometheus-shoot
        key: token
    followRedirects: true
    namespaces:
      names:
      - kube-system
    role: Pod
    tlsConfig:
      insecureSkipVerify: true
  metricRelabelings:
  - sourceLabels:
    - __name__
    action: keep
    regex: (network|service_network)_.+
  relabelings:
  - action: replace
    replacement: network-traffic-gauger-agents
    targetLabel: job
  - sourceLabels: [__meta_kubernetes_pod_name,__meta_kubernetes_pod_container_port_name,__meta_kubernetes_namespace]
    regex: network-traffic-gauger-(.+);metrics;kube-system
    action: keep
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - sourceLabels: [__meta_kubernetes_pod_name]
    targetLabel: pod
  - sourceLabels: [__meta_kubernetes_pod_node_name]
    targetLabel: node
  - targetLabel: __address__
    replacement: kube-apiserver:443
  - sourceLabels: [__meta_kubernetes_pod_name,__meta_kubernetes_pod_container_port_number]
    separator: ;
    regex: (.+);(.+)
    targetLabel: __metrics_path__
    replacement: /api/v1/namespaces/kube-system/pods/${1}:${2}/proxy/metrics
    action: replace
