#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname $0)/.."

if [ -z "${GOPATH:-}" ]; then
  # workaround. Can be dropped after revendoring gardener/gardener
  mkdir -p $HOME/go
  export GOPATH=$HOME/go
fi

export GOTOOLCHAIN=local
make verify-extended
